<a href="https://colab.research.google.com/github/varshinipilla6-dot/PILLA-VARSHINI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Remove Duplicates from 1D Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5])

unique_arr = np.unique(arr)

print(unique_arr)

[1 2 3 4 5]


2. Remove Duplicate Rows from 2D Array

In [ ]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [1, 2],
                [5, 6]])

unique_rows = np.unique(arr, axis=0)

print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


3. Remove Duplicate Columns

In [ ]:
unique_cols = np.unique(arr, axis=1)
print(unique_cols)

[[1 2]
 [3 4]
 [1 2]
 [5 6]]


4. Get Unique Values + Counts

In [ ]:
values, counts = np.unique(arr, return_counts=True)

print("Values:", values)
print("Counts:", counts)

Values: [1 2 3 4 5 6]
Counts: [2 2 1 1 1 1]


5. Get Unique Values + Index

In [ ]:
values, index = np.unique(arr, return_index=True)

print("Unique values:", values)
print("First occurrence index:", index)

Unique values: [1 2 3 4 5 6]
First occurrence index: [0 1 2 3 6 7]


Data Cleaning & Data Preparation using NumPy 👇

In [ ]:
import numpy as np

Step 2: Load/Create Data

In [ ]:
data = np.array([[1, 'A', 10],
                  [2, 'B', 20],
                  [1, 'A', 10],
                  [3, 'C', 30],
                  [2, 'B', 20]])

Step 3: Remove Duplicate Values

Step 4: Handle Missing Values

In [ ]:
ratings = data[:, 2].astype(float)
mean = np.nanmean(ratings)
ratings = np.where(np.isnan(ratings), mean, ratings)
data[:, 2] = ratings

Step 5: Clean Text Data

```
# This is formatted as code
```



In [ ]:
data[:, 1] = np.char.lower(data[:, 1].astype(str))

Step 6: Convert Data Types

In [ ]:
data[:, 2] = data[:, 2].astype(float)

Step 7: Remove Invalid Data

In [ ]:
mask = (data[:, 2].astype(float) <= 5) & (data[:, 0].astype(int) > 0)
data = data[mask]
print(data)

[]


Step 8: Feature Engineering

In [ ]:
cost_per_person = data[:, 2].astype(float) / 2
data = np.column_stack((data, cost_per_person))